import streamlit as st

from engine import api
from docx_export import markdown_to_docx_bytes
from style import empty_state, inject_css

inject_css()
st.title("Literature Review")
st.caption("Generate a theme-organized synthesis across your library, with sources cited inline.")

try:
    papers = api.list_papers_cached()
except Exception:
    papers = []
completed_papers = [p for p in papers if p["status"] == "completed"]
options = {p["id"]: (p.get("title") or p["filename"]) for p in completed_papers}

topic = st.text_input("Review topic", placeholder="e.g. Transformer-based approaches to long-context retrieval")
selected_ids = st.multiselect(
    "Scope (optional)", options=list(options.keys()), format_func=lambda pid: options[pid]
)

if st.button("Generate Review", type="primary", disabled=not topic.strip()):
    with st.spinner("Synthesizing across sources..."):
        try:
            result = api.literature_review(topic, selected_ids or None)
            st.session_state["lit_review_result"] = result
        except api.APIError as e:
            st.error(f"Couldn't generate a review: {e.detail}")

if "lit_review_result" in st.session_state:
    st.divider()
    result = st.session_state["lit_review_result"]
    st.markdown(result["review"])

    docx_bytes = markdown_to_docx_bytes(
        title=f"Literature Review: {result['topic']}",
        markdown_text=result["review"],
        subtitle="Generated by GraphRAG Research Assistant",
    )
    safe_topic = "".join(c if c.isalnum() or c in " -_" else "" for c in result["topic"])[:60].strip() or "review"
    st.download_button(
        "Download as Word document",
        data=docx_bytes,
        file_name=f"literature-review-{safe_topic}.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
elif not topic:
    empty_state("Start a review", "Enter a topic above and generate a synthesis grounded in your library.")
